# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20171004_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=10),
        ),
    ]
